# SQL Server produccion
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Redis produccion
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# JPA produccion
spring.jpa.hibernate.ddl-auto=validate

logging.level.com.alfahospital=ERROR
logging.file.name=/var/log/alfa/alfa-auth-service.log

# Frontend URLs
app.frontend.url=${APP_FRONTEND_URL:http://localhost:4200}
app.reset-password.url=${APP_FRONTEND_URL:http://localhost:4200}/auth/reset-password