# SQL Server produccion
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Redis produccion
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# JPA produccion
spring.jpa.hibernate.ddl-auto=validate

logging.level.com.alfahospital=ERROR

# Frontend URLs
app.frontend.url=http://57.156.67.36
app.reset-password.url=http://57.156.67.36/auth/reset-password