# SQL Server local
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=alfa_auth;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=AlfaHospital2024!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Redis local
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=alfa-hospital-secret-key-2024-muy-larga-para-seguridad
jwt.expiration=86400000

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=alfa
spring.rabbitmq.password=alfa1234

# Logs
logging.level.com.alfahospital=DEBUG

app.frontend.url=${FRONTEND_URL}